version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    container_name: es01
    user: root
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ~/elasticsearch/data01:/tmp/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:7.6.1
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - elastic

  recipe:
    image: alexsanjoseph/customized-recipe:v1
    container_name: recipe
    ports:
      - 8501:8501
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ES_WAIT_TIME: 40
    networks:
      - elastic
    command: bash -c "python3 datauploads/upload_all.py && streamlit run src/ui2.py"

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge
